import Head from "next/head";
import { useState } from "react";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
import { FaRegCalendarAlt } from "react-icons/fa";
import { GoLocation } from "react-icons/go";

const EVENTS = [
  {
    name: "Synchronize Fest",
    img: "https://synchronizefestival.com/prod/assets/images/homo0.jpg",
    date: "1-3 September 2023",
    location: "Gambir Expo Kemayoran, Jakarta",
  },
  {
    name: "Pestapora",
    img: "https://exhibition.jiexpo.com/wp-content/uploads/sites/5/2022/07/pestapora.jpg",
    date: "23-25 September 2023",
    location: "Gambir Expo Kemayoran, Jakarta",
  },
];

export default function Home() {
  const [thisMonth, setThisMonth] = useState([...EVENTS]);
  const [events, setEvents] = useState([1, 2, 3, 4]);

  return (
    <div className="flex justify-center">
      <Head>
        <title>Rundownizer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-4 py-6 max-w-md">
        <h1 className="text-lg font-bold">Welcome to Rundownizer!</h1>
        <p className="font-light text-[#677487]">
          Solusi bingung nonton konser kalo artisnya ramean.
        </p>

        <div className="mt-8">
          <p className="text-lg mb-2">Bulan Ini</p>
          <div className="overflow-wrapper">
            {thisMonth.map((event) => {
              return (
                <div className="card w-5/6 mr-4">
                  <div
                    className="w-full h-[158px] rounded-lg bg-slate-300 bg-hero"
                    style={{ backgroundImage: `url(${event.img})` }}
                  ></div>
                  <div className="flex justify-between items-center mt-2">
                    <p className="text-lg my-1">{event.name}</p>
                    <div className="bg-[#A6F4C5] rounded-full px-3 text-xs py-1 font-light">
                      Hari Ini
                    </div>
                  </div>
                  <div className="flex text-slate-500 items-center mb-1 text-sm font-light">
                    <button className="mr-1">
                      <FaRegCalendarAlt />
                    </button>
                    <p>{event.date}</p>
                  </div>
                  <div className="flex text-slate-500 items-center text-sm font-light">
                    <button className="mr-1">
                      <GoLocation />
                    </button>
                    <p>{event.location}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        <div className="mt-8">
          <p className="mb-4">Akan Datang</p>
          <div className="grid grid-cols-2 gap-4">
            {events.map((event) => {
              return (
                <div className="">
                  <div className="rounded-lg bg-slate-300 aspect-ratio bg-event"></div>
                  <p className="font-bold mb-1">Syncronize Fest</p>
                  <div className="flex text-slate-500 items-center mb-1 text-sm">
                    <button className="mr-1">
                      <FaRegCalendarAlt />
                    </button>
                    <p>1-3 September 2023</p>
                  </div>
                  <div className="flex text-slate-500 items-start text-sm">
                    <button className="mt-1 mr-1">
                      <GoLocation />
                    </button>
                    <p>Gambir Expo Kemayoran, Jakarta</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </div>
  );
}
